/** Valores iniciales del formulario (mismo formato que POST /comprasmx/snapshot). */
export const DEFAULT_ENTIDADES_FEDERATIVAS = [
  "BAJA CALIFORNIA",
  "BAJA CALIFORNIA SUR",
  "SONORA",
  "CIUDAD DE MÉXICO",
  "CHIHUAHUA",
  "COLIMA",
  "DURANGO",
  "JALISCO",
  "NAYARIT",
  "SINALOA",
  "YUCATÁN",
] as const;

export const DEFAULT_PALABRAS_CLAVE = [
  "Jardinería",
  "Limpieza",
  "Fumigación",
  "Control de plagas",
  "Áreas verdes",
  "Sanitización",
  "Desinfección",
  "Adquisición de víveres",
  "Insumos alimenticios",
  "Aseo",
  "Conservación",
] as const;

/** Respaldo si GET /comprasmx/entidades falla (sincronizado con backend `ENTIDADES_FEDERATIVAS_TODAS`). */
export const ENTIDADES_TODAS_FALLBACK = [
  "AGUASCALIENTES",
  "BAJA CALIFORNIA",
  "BAJA CALIFORNIA SUR",
  "CAMPECHE",
  "COAHUILA DE ZARAGOZA",
  "COLIMA",
  "CHIAPAS",
  "CHIHUAHUA",
  "CIUDAD DE MÉXICO",
  "DURANGO",
  "GUANAJUATO",
  "GUERRERO",
  "HIDALGO",
  "JALISCO",
  "MÉXICO",
  "MICHOACÁN DE OCAMPO",
  "MORELOS",
  "NAYARIT",
  "NUEVO LEÓN",
  "OAXACA",
  "PUEBLA",
  "QUERÉTARO",
  "QUINTANA ROO",
  "SAN LUIS POTOSÍ",
  "SINALOA",
  "SONORA",
  "TABASCO",
  "TAMAULIPAS",
  "TLAXCALA",
  "VERACRUZ DE IGNACIO DE LA LLAVE",
  "YUCATÁN",
  "ZACATECAS",
] as const;
